/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarList: typeof import('./src/components/Avatar/AvatarList.vue')['default']
    AvatarMenu: typeof import('./src/components/Avatar/AvatarMenu.vue')['default']
    Breadcrumb: typeof import('./src/components/Themes/Breadcrumb.vue')['default']
    DarkModeToggle: typeof import('./src/components/Themes/DarkModeToggle.vue')['default']
    DropDown: typeof import('./src/components/Menu/DropDown.vue')['default']
    Editor: typeof import('./src/components/Editor/Editor.vue')['default']
    FullScreen: typeof import('./src/components/Themes/FullScreen.vue')['default']
    Header1: typeof import('./src/components/layouts/Header1.vue')['default']
    HeaderTabs: typeof import('./src/components/layouts/HeaderTabs.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconFontIcon: typeof import('./src/components/Icon/IconFontIcon.vue')['default']
    Iconify: typeof import('./src/components/Icon/Iconify.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
    LoginForm: typeof import('./src/components/Form/LoginForm.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MenuItem: typeof import('./src/components/Menu/MenuItem.vue')['default']
    NetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
    Notice: typeof import('./src/components/Notice/Notice.vue')['default']
    NoticeMessageList: typeof import('./src/components/Notice/NoticeMessageList.vue')['default']
    Notification: typeof import('./src/components/Notice/Notification.vue')['default']
    Popover: typeof import('./src/components/Table/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/Menu/SubMenu.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    ThemeSetting: typeof import('./src/components/Themes/ThemeSetting.vue')['default']
    VForm: typeof import('./src/components/Form/VForm.vue')['default']
    VFormItem: typeof import('./src/components/Form/VFormItem.vue')['default']
    VFormLayout: typeof import('./src/components/Form/VFormLayout.vue')['default']
    VTable: typeof import('./src/components/Table/VTable.vue')['default']
    VTableColumn: typeof import('./src/components/Table/VTableColumn.vue')['default']
    VueEcharts: typeof import('./src/components/Charts/VueEcharts.vue')['default']
  }
}
